### ISSUE TITLE
npm install EINTEGRITY fails with yargs-parser

### ISSUE THREAD

**Issue by spdustin** [contentful/starter-gatsby-blog#121]
During `npm install`, an `EINTEGRITY` error prevents the process from completing. It looks like the offending package is `yargs-parser`, which is a dependency of `webpack-dev-server`, `gatsby`, and `contentful-import`.

> `error sha512-C6kB/WJDiaxONLJQnF8ccx9SEeoTTLek8RVbaOIsrAUS8VrBEXfmeSnCZxygc+XC2sNMBIwOOnfcxiynjHsVSQ== integrity checksum failed when using sha512: wanted sha512-C6kB/WJDiaxONLJQnF8ccx9SEeoTTLek8RVbaOIsrAUS8VrBEXfmeSnCZxygc+XC2sNMBIwOOnfcxiynjHsVSQ== but got sha512-3lbsNRf/j+A4QuSZfDRA7HRSfWrzO0YjqTJd5kjAq37Zep1CEgaYmrH9Q3GwPiB9cHyd1Y1UwggGhJGoxipbzg==. (15450 bytes)`

The locked version of `yargs-parser` (as a dependency of those packages) is *13.1.2*

**Comment by jo-sm** [comment]
Hi @spdustin, I just ran a fresh `npm install` of the latest master commit and didn't run into this issue -- it worked as expected. I'm going to close this issue, but please try again and reopen the issue if you are still experiencing it.

**Comment by Gcarter17** [comment]
still experiencing this issue, fresh install first time setting up...
