### ISSUE TITLE
setup.js config delivery access token has incorrect env var name

### ISSUE THREAD

**Issue by mattgabor** [contentful/starter-gatsby-blog#133]
https://github.com/contentful/starter-gatsby-blog/blob/7ac74c7c38a65cb564647ca712e52dfb9ae74d17/bin/setup.js#L50

@gregferg I think this should be `CONTENTFUL_ACCESS_TOKEN` instead of `CONTENTFUL_ACCESS_TOKEN_TOKEN`

**Comment by gregferg** [comment]
Thanks @mattgabor! Fixed in https://github.com/contentful/starter-gatsby-blog/pull/140.
