### ISSUE TITLE
Npm Install fails

### ISSUE THREAD

**Issue by PaulBriar** [contentful/starter-gatsby-blog#14]
Attempting to npm install after cloning the repo fails with no clear fix.  Here is the summary terminal output:

**Summary:**
fatal error: too many errors emitted, stopping now [-ferror-limit=]
10 warnings and 20 errors generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/paul.briar/Desktop/Learning/Gatsby/starter-gatsby-blog/node_modules/sharp
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.20.5 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.20.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/paul.briar/.npm/_logs/2019-07-10T12_51_08_422Z-debug.log

**Comment by jasloe** [comment]
Same issue here.

**Comment by jasloe** [comment]
As a temporary fix, you can use nvm to install version 11.15.0.

```
nvm install 11.15.0
nvm use 11.15.0
yarn install
```

**Comment by mrbowes** [comment]
@jasloe - had same issue. Appreciate your workaround - that worked!

**Comment by jasloe** [comment]
No problem. Having trouble getting the GraphiQL explorer working. The GraphiQL display does appear though without the Explorer tab. Did you have the same issue?

**Comment by vedmant** [comment]
I have the same issue, looks like there is dependency "sharp" which fails to build on Node 12. The old version is used by old "gatsby-plugin-sharp" version. So it needs upgarde of "gatsby-plugin-sharp".

**Comment by johndpotts** [comment]
@jasloe worked for me

**Comment by arpl** [comment]
Fixed in #47

**Comment by Preshonyee** [comment]
> As a temporary fix, you can use [nvm](https://github.com/nvm-sh/nvm) to install version 11.15.0 of node.
> 
> ```
> nvm install 11.15.0
> nvm use 11.15.0
> yarn install
> ```



> As a temporary fix, you can use [nvm](https://github.com/nvm-sh/nvm) to install version 11.15.0 of node.
> 
> ```
> nvm install 11.15.0
> nvm use 11.15.0
> yarn install
> ```

Thanks a lot. This solved the issue for me.

**Comment by axe312ger** [comment]
If you still got issues, you can use the branch from #126
