### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by skikirkwood** [contentful/starter-gatsby-blog#50]
I'm testing signing up as a new user/developer and the new user onboarding in the web app has you install this demo. The "npm install" step failed. Log file is attached.
[2020-01-23T18_38_31_462Z-debug.log](https://github.com/contentful/starter-gatsby-blog/files/4104905/2020-01-23T18_38_31_462Z-debug.log)

<img width="1657" alt="Screen Shot 2020-01-23 at 10 02 58 AM" src="https://user-images.githubusercontent.com/1205597/73014326-cff94a80-3dce-11ea-8eb6-a8b0109fa1ca.png">

**Comment by skikirkwood** [comment]
My issue was due to using an old version of Node.js. Closing this.

**Comment by lengband** [comment]
![image](https://user-images.githubusercontent.com/26566045/184907160-0fb29a82-e39b-461a-b807-8a32f2d575b9.png)
